### ISSUE TITLE
LocalFile cache confusion

### ISSUE THREAD

**Issue by rburgst** [gatsbyjs/gatsby-source-wordpress-experimental#153]
Unfortunately I cannot share my wordpress instance, however let me explain my findings.

I have multiple pages that reference the same image in different sizes.

in `fetchNodeHtmlImageMediaItemNodes` we can see that the `imageNode.id` is saved to the cache

```
    if (imageNode) {
      // save any fetched media items in our global media item cache
      _store.default.dispatch.imageNodes.pushNodeMeta({
        sourceUrl: htmlImgSrc,
        id: imageNode.id,
        modifiedGmt: imageNode.modifiedGmt
      }); // match is the html string of the img tag
```

In my case the `imageNode` is a `MediaItem`
```
  ...
  "remoteFile": {
    "id": "f61fe9db-337d-5f25-8ac0-35a9a8a9f501"
  },
  "localFile": {
    "id": "f61fe9db-337d-5f25-8ac0-35a9a8a9f501"
  },
  "parent": null,
  "internal": {
    "contentDigest": "2001149f43ce77ed8758db8595e7e8fd",
    "type": "WpMediaItem",
    "counter": 77,
    "owner": "gatsby-source-wordpress-experimental"
  },
  "type": "MediaItem",
  "nodeType": "MediaItem",
  "children": []
```

However the `pushNodeMeta` call also causes the `nodeMetaByUrl` lookup table to be set / overwritten.

```
    pushNodeMeta(state, {
      id,
      sourceUrl,
      modifiedGmt
    }) {
      state.nodeIds.push(id);
      state.nodeMetaByUrl[(0, _fetchReferencedMediaItems.stripImageSizesFromUrl)(sourceUrl)] = {
        id,
        modifiedGmt
      };
      return state;
    }
```

However in `getFileNodeByMediaItemNode` we pull the node meta out and treat it as if it was a localFile

```
const getFileNodeByMediaItemNode = async ({
  mediaItemNode,
  helpers
}) => {
  const {
    sourceUrl,
    modifiedGmt,
    mediaItemUrl,
    databaseId
  } = mediaItemNode;
  const fileUrl = sourceUrl || mediaItemUrl;

  if (!fileUrl) {
    helpers.reporter.warn((0, _formatLogMessage.formatLogMessage)(`Couldn't find source url for media item #${databaseId}`));
    return null;
  }

===>   const existingNodeMeta = getFileNodeMetaBySourceUrl(fileUrl);

  if ( // if we already have this image
  existingNodeMeta && existingNodeMeta.id && // and it hasn't been modified
  existingNodeMeta.modifiedGmt === modifiedGmt) {
    const node = await helpers.getNode(existingNodeMeta.id);
    return node;
  }

  return null;
};
```

So in my case the `pushNodeMeta` gets called multiple times, the first few instances with the correct remoteFileNode `id` and `url` coming from `createRemoteMediaItemNode`
```
 // so we can touch this node next time
  // and so we can easily access the id by source url later

  _store.default.dispatch.imageNodes.pushNodeMeta({
    id: remoteFileNode.id,
    sourceUrl: mediaItemUrl,
    modifiedGmt
  });
```

However, a bit later we get the call with a resized version of the url (coming from `fetchNodeHtmlImageMediaItemNodes`). Now `pushNodeMeta` gets called with the id of the imageNode.  Since both urls are normalized (`stripImageSizesFromUrl`) the cache in `nodeMetaByUrl` gets overwritten and it now points to an `ImageNode` rather than a `localFile`.

Now every call to `getFileNodeByMediaItemNode` will result in the ImageNode being returned rather than the FileNode.

In the end the build fails with 

```
The "path" argument must be one of type string, Buffer, or URL. Received type undefined



  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of ty  pe string, Buffer, or URL. Received type undefined
  ```

called from `replaceNodeHtmlImages` when going through `htmlMatchesWithImageResizes` because

```
      if (imageResize) {
        imgOptions.fluid = imageResize
        ReactGatsbyImage = React.createElement(Img, imgOptions, null)
      } else {
        const { fileNode } = matchResize

        const fileName = `${fileNode.internal.contentDigest}/${fileNode.base}`
```

the `fileNode` here is no longer a real `fileNode` but the `imageNode`.

**Comment by rburgst** [comment]
anyone home?

**Comment by TylerBarnes** [comment]
Hey @rburgst I was out on vacation the last couple weeks. Thanks for this detailed description of the problem, this is really helpful. So to reproduce I need to use the same image in 2 different fields but set a different size for each field?

**Comment by rburgst** [comment]
Yes, in my case the default (no specific size) gets handled first and leads to the correct file node being stored in the cache. Then inside an html tag the same image with a different size spec gets referenced and leads the previous filenode cache entry to be overwritten with a mediaItem node. I have created a patch that solves the problem for me but am not 100% sure if the solution is a good one. Will post the MR today.

**Comment by TylerBarnes** [comment]
This is a really hard one to reproduce! Is there any way you'd be able to email me your /graphql API url? (tyler@gatsbyjs.com).

If that's not possible can you share more specifically in what kinds of fields these images are stored in and what the file path & name is for each? That might help me figure out how to reproduce. If I can reproduce then I can write a test for this which would be nice. Your code looks good but it's hard to merge it without being able to reproduce the problem.

In the last couple releases I also fixed some other caching issues around images which might (but probably doesn't) fix this issue so It's probably worth trying latest.

Thanks for your patience and clear description with this!

**Comment by rburgst** [comment]
I will try with the latest master version and let you know. Unfortunately our server is behind VPNs.

**Comment by rburgst** [comment]
It seems the bug still exists in latest master. Will try and analyze again / rebase my patch

**Comment by rburgst** [comment]
I am fairly certain the bug is caused by a custom ACF with HTML content that contains html such as this:

```html
<a href="http://dockerhost:8000/wp-content/uploads/2018/05/imagename-300x163-1.jpg"><img class="alignleft size-full wp-image-9076767" src="http://dockerhost:8000/wp-content/uploads/2018/05/imagename-300x163-1.jpg" alt="" width="300" height="163" /></a>
```

**Comment by rburgst** [comment]
ok, I did some more digging. 

The problem appears if I have 2 pages that virtually have the identical content (I have 2 translations of the same page). Both have a HTML ACF which references the image 

```html
  <img class="alignleft size-full wp-image-9076767" src="http://dockerhost:8000/wp-content/uploads/2018/05/imagename-300x163-1.jpg" alt="" width="300" height="163" />
```

To me it looks like we have a race condition, we first store the filenode in `state.nodeMetaByUrl["http://dockerhost:8000/wp-content/uploads/2018/05/imagename-300x163-1.jpg"]` called from `createRemoteMediaItemNode`

  callstack
     ```
    pushNodeMeta(), image-nodes.js:32
createRemoteMediaItemNode(), create-remote-media-item-node.js:219
Async call from async function
createRemoteMediaItemNode(), create-remote-media-item-node.js:108
retryPromise(), fetch-referenced-media-items.js:147
anonymous(), fetch-referenced-media-items.js:65
run(), index.js:249
_tryToStartAnother(), index.js:197
anonymous(), index.js:263
add(), index.js:244
pushPromiseOntoRetryQueue(), fetch-referenced-media-items.js:56
createMediaItemNode(), fetch-referenced-media-items.js:132
processTicksAndRejections(), task_queues.js:93
Async call from async function
createMediaItemNode(), fetch-referenced-media-items.js:116
anonymous(), fetch-referenced-media-items.js:348
retryPromise(), fetch-referenced-media-items.js:348
pushPromiseOntoRetryQueue(), fetch-referenced-media-items.js:56
fetchMediaItemsBySourceUrl(), fetch-referenced-media-items.js:305
Async call from async function
fetchMediaItemsBySourceUrl(), fetch-referenced-media-items.js:285
fetchReferencedMediaItemsAndCreateNodes(), fetch-referenced-media-items.js:498
fetchNodeHtmlImageMediaItemNodes(), process-node.js:185
Async call from async function
fetchNodeHtmlImageMediaItemNodes(), process-node.js:152
replaceNodeHtmlImages(), process-node.js:415
processNodeString(), process-node.js:631
processNode(), process-node.js:667
```

a bit later we overwrite this entry with an imageNode called from `fetchNodeHtmlImageMediaItemNodes`

```
    if (imageNode) {
      // save any fetched media items in our global media item cache
      _store.default.dispatch.imageNodes.pushNodeMeta({
        sourceUrl: htmlImgSrc,
        id: imageNode.id,
        modifiedGmt: imageNode.modifiedGmt
      }); // match is the html string of the img tag
```

callstack

```
pushNodeMeta(), image-nodes.js:32
fetchNodeHtmlImageMediaItemNodes(), process-node.js:256
Async call from async function
fetchNodeHtmlImageMediaItemNodes(), process-node.js:152
replaceNodeHtmlImages(), process-node.js:415
processNodeString(), process-node.js:631
processNode(), process-node.js:667
```

now `state.nodeMetaByUrl["http://dockerhost:8000/wp-content/uploads/2018/05/imagename-300x163-1.jpg"]` points to an `imageNode`.

then we enter `createRemoteMediaItemNode` a 2nd time (this time because the `img` tag also had a `wp-image-9076767` tag (probably)). Now `getFileNodeByMediaItemNode` will return the `imageNode` rather than the filenode which will cause the problem.

**Comment by rburgst** [comment]
IMHO in https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/src/steps/source-nodes/create-nodes/process-node.js#L263 we must push the localFile node rather than the imageNode

**Comment by TylerBarnes** [comment]
I agree, just want to make sure I can add a test in for this. Thanks again!

**Comment by TylerBarnes** [comment]
Published in `gatsby-source-wordpress-experimental@1.4.2`!

Thanks so much for identifying this issue and fixing it! I wasn't able to reproduce as hard as I was trying to :p But your change is logical, works, and didn't break the existing image tests, so merging this is a no-brainer. This is an edge case bug but one I'm sure many would've run into in the future, so again thanks so much for this meaningful contribution! Also thanks for being so patient with this, I'm trying to work on getting on top of all these issues so I can respond a bit quicker in the future.

Cheers!
